app = 'temporal-worker-wild-surf-7014'
primary_region = 'ewr'

[build]
  dockerfile = '../apps/worker/fly.Dockerfile'
  ignorefile = '../apps/worker/.dockerignore'

[env]
  TEMPORAL_TASK_QUEUE = 'general'
  NODE_ENV = 'production'
  TEMPORAL_WORKER_STATUS_HTTP_PORT = '3001'
  TEMPORAL_WORKER_METRIC = 'PROMETHEUS'
  TEMPORAL_METRICS_PROMETHEUS_ADDRESS = '0.0.0.0:9464'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  interval = '10m0s'
  timeout = '9m'
  grace_period = '10s'
  method = 'GET'
  path = '/'

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 1

[[metrics]]
  port = 9464
  path = '/metrics'
  https = false