app = 'twilio-worker'
primary_region = 'ewr'

[build]
  dockerfile = '../apps/twilio-worker/fly.Dockerfile'
  ignorefile = '../apps/twilio-worker/.dockerignore'

[env]
  NODE_ENV = 'production'
  TEMPORAL_TASK_QUEUE = 'twilio'
  TEMPORAL_WORKER_STATUS_HTTP_PORT = '3001'
  TEMPORAL_WORKER_METRIC = 'PROMETHEUS'
  TEMPORAL_METRICS_PROMETHEUS_ADDRESS = '0.0.0.0:9464'

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 1

[[metrics]]
  port = 9464
  path = '/metrics'
  https = false
